# Generated by Django 2.2.6 on 2019-11-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0002_auto_20191101_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='commit',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commit.Commit'),
        ),
    ]
