# Generated by Django 2.2.6 on 2019-11-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
